# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab8a5bae305a1d6811f27e390a2629e2e6c72312fa0dc8e4ee0c62fb4feb4d7efff61f7533d480e23d6408aba73869e0760d1a4ac778c8e6dfadbba6ae49b053

test:
  secret_key_base: a75b4812a654adc295015f65697ae47958a70f6b725e85f50cb22698901be615a66f7d9d8cedd324f16c7014aee35126eabe8dc7c5bcbe69dd20bd069af1dc24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
